import React from 'react';
import { FaRobot, FaUserShield, FaChartLine, FaAppleAlt, FaComments, FaRegSmile, FaCalculator, FaPalette } from 'react-icons/fa';

const features = [
    {
        icon: <FaRobot className="text-green-500 text-3xl" />,
        title: 'AI-Powered Diet Plan',
        desc: 'Get a personalized diet plan generated by advanced AI, tailored to your health, preferences, budget, and goals. Your plan updates as your profile changes!'
    },
    {
        icon: <FaUserShield className="text-blue-500 text-3xl" />,
        title: 'Profile & Health Tracking',
        desc: 'Easily manage your profile, track your health metrics (BMI, BMR, TDEE, Calorie Needs), and update your details anytime.'
    },
    {
        icon: <FaCalculator className="text-purple-500 text-3xl" />,
        title: 'Smart Calculators',
        desc: 'Use beautiful, interactive calculators for BMI, BMR, TDEE, and Calorie Needs. Instantly see your results and what they mean.'
    },
    {
        icon: <FaAppleAlt className="text-red-400 text-3xl" />,
        title: 'Modern Diet Plan UI',
        desc: 'View your diet plan in a stunning, easy-to-read timeline. See meal names, calories, macros, and budgets at a glance.'
    },
    {
        icon: <FaComments className="text-pink-400 text-3xl" />,
        title: 'Chat with AI',
        desc: 'Ask the AI anything about your diet plan, nutrition, or health. Get instant, friendly answers in a beautiful chat interface.'
    },
    {
        icon: <FaRegSmile className="text-yellow-400 text-3xl" />,
        title: 'Change Your Plan via Chat',
        desc: 'Want to tweak your plan? Just ask the AI in chat! Your plan updates and saves automatically.'
    },
    {
        icon: <FaPalette className="text-indigo-400 text-3xl" />,
        title: 'Beautiful, Modern Design',
        desc: 'Enjoy a glassmorphism-inspired, mobile-friendly UI with smooth animations and engaging visuals everywhere.'
    },
];

const About = () => {
    return (
        <div className="min-h-screen bg-white dark:bg-gray-900 px-4 py-12">
            <div className="max-w-3xl mx-auto bg-white dark:bg-gray-900 rounded-2xl shadow-lg border border-green-100 dark:border-gray-800 p-8">
                <h1 className="text-3xl font-bold text-green-700 dark:text-lime-300 mb-6">About Pro Diet</h1>
                <p className="text-gray-700 dark:text-gray-200 mb-4">Your all-in-one, AI-powered diet and health companion. Discover how ProDiet can help you eat smarter, live healthier, and reach your goals—effortlessly.</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl w-full">
                    {features.map((f, i) => (
                        <div key={i} className="backdrop-blur-md bg-white/70 border border-green-100 rounded-2xl shadow-xl p-7 flex flex-col items-center text-center hover:scale-105 hover:shadow-2xl transition-transform duration-300">
                            <div className="mb-3">{f.icon}</div>
                            <h2 className="text-2xl font-bold text-green-700 dark:text-lime-300 mb-2">{f.title}</h2>
                            <p className="text-gray-600 text-base md:text-lg dark:text-gray-200">{f.desc}</p>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default About; 